### ISSUE TITLE
serve --profile

### ISSUE THREAD

**Issue by marcmetz** [BretFisher/jekyll-serve#10]
Hi Bret, I tried to execute that command here:
`docker run -v $(pwd):/site bretfisher/jekyll serve --profile`

I always receive this error message. Can you tell me if I'm doing anything wrong?
```
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find jekyll-feed-0.11.0 in any of the sources (Bundler::GemNotFound)
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `map!'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `materialize'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:170:in `specs'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:237:in `specs_for'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:226:in `requested_specs'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:108:in `block in definition_method'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:20:in `setup'
from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler.rb:107:in `setup'
from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
from /usr/local/bundle/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
from /usr/local/bundle/bin/jekyll:23:in `load'
from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

What still works without problem is `docker-compose up`:
`docker run -v $(pwd):/site bretfisher/jekyll-serve`

**Comment by BretFisher** [comment]
On the first command you’d first need a bundle install
