### ISSUE TITLE
Fails when Nokogiri gem included in website

### ISSUE THREAD

**Issue by danwt** [BretFisher/jekyll-serve#69]
Hi, I'm using `docker run -p 4000:4000 -v $(pwd):/site bretfisher/jekyll-serve` to serve [this website](https://github.com/informalsystems/modelator/tree/main/jekyll) and I receive the following

Output of cmd:

```
Fetching gem metadata from https://rubygems.org/.........
Fetching rake 13.0.6
Installing rake 13.0.6
Using public_suffix 4.0.6
Using bundler 2.3.7
Using colorator 1.1.0
Fetching concurrent-ruby 1.1.10
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Fetching gemoji 3.0.1
Using rb-fsevent 0.11.1
Fetching rexml 3.2.5
Using liquid 4.0.3
Using mercenary 0.4.0
Using rouge 3.28.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Fetching rubyzip 2.3.2
Fetching racc 1.6.0
Fetching rainbow 3.1.1
Fetching webrick 1.7.0
Using addressable 2.8.0
Using em-websocket 0.5.3
Using sassc 2.4.0
Using rb-inotify 0.10.1
Using pathutil 0.16.2
Using terminal-table 2.0.0
Fetching jekyll-sass-converter 2.2.0
Using listen 3.7.1
Using jekyll-watch 2.2.1
Installing rainbow 3.1.1
Installing jekyll-sass-converter 2.2.0
Installing rubyzip 2.3.2
Installing gemoji 3.0.1
Installing webrick 1.7.0
Installing racc 1.6.0 with native extensions
Installing rexml 3.2.5
Installing concurrent-ruby 1.1.10
Fetching kramdown 2.3.2
Using i18n 1.10.0
Installing kramdown 2.3.2
Using kramdown-parser-gfm 1.1.0
Fetching jekyll 4.2.2
Installing jekyll 4.2.2
Fetching jekyll-pdf-embed 1.1.2.1
Fetching jekyll-remote-theme 0.4.3
Fetching jekyll-seo-tag 2.8.0
Installing jekyll-remote-theme 0.4.3
Installing jekyll-pdf-embed 1.1.2.1
Installing jekyll-seo-tag 2.8.0
Fetching nokogiri 1.13.3 (aarch64-linux)
Fetching just-the-docs 0.3.3
Installing just-the-docs 0.3.3
Installing nokogiri 1.13.3 (aarch64-linux)
Fetching jekyll-spaceship 0.10.2
Installing jekyll-spaceship 0.10.2
Bundle complete! 10 Gemfile dependencies, 40 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from rubyzip:
RubyZip 3.0 is coming!
**********************

The public API of some Rubyzip classes has been modernized to use named
parameters for optional arguments. Please check your usage of the
following classes:
  * `Zip::File`
  * `Zip::Entry`
  * `Zip::InputStream`
  * `Zip::OutputStream`

Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
/usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri.rb:10:in `require_relative'
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri.rb:10:in `<top (required)>'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship/cores/manager.rb:3:in `require'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship/cores/manager.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship.rb:5:in `require'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `each'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `block in require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `each'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler.rb:176:in `require'
	from /usr/local/bundle/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
/usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/extension.rb:7:in `require_relative': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/2.7/nokogiri.so) - /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/2.7/nokogiri.so (LoadError)
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri.rb:10:in `require_relative'
	from /usr/local/bundle/gems/nokogiri-1.13.3-aarch64-linux/lib/nokogiri.rb:10:in `<top (required)>'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship/cores/manager.rb:3:in `require'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship/cores/manager.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship.rb:5:in `require'
	from /usr/local/bundle/gems/jekyll-spaceship-0.10.2/lib/jekyll-spaceship.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `each'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `block in require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `each'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `require'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler.rb:176:in `require'
	from /usr/local/bundle/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
```

Also, `docker run -v $(pwd):/site bretfisher/jekyll bundle install` fails

```
docker run -v $(pwd):/site bretfisher/jekyll bundle install
/usr/local/bundle/gems/bundler-2.3.9/lib/bundler/definition.rb:481:in `materialize': Could not find jekyll-remote-theme-0.4.3, jekyll-spaceship-0.10.2, jekyll-seo-tag-2.8.0, jekyll-pdf-embed-1.1.2.1, rake-13.0.6, webrick-1.7.0, just-the-docs-0.3.3, kramdown-2.3.2, rubyzip-2.3.2, gemoji-3.0.1, nokogiri-1.13.3-aarch64-linux, rainbow-3.1.1, concurrent-ruby-1.1.10, rexml-3.2.5, racc-1.6.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/definition.rb:190:in `specs'
	from /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/definition.rb:238:in `specs_for'
	from /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/runtime.rb:18:in `setup'
	from /usr/local/bundle/gems/bundler-2.3.9/lib/bundler.rb:151:in `setup'
	from /usr/local/bundle/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

Thank you. I like the tool and have used it successfully in other projects.

**Comment by BretFisher** [comment]
Looks like you hit an issue with arm64 and some gems, which need glibc compatibility installed by the system package manager (apk), so I just updated the dockerfile with `gcompat`. Pull the latest image and see if that works.

Issue and fix: https://github.com/sparklemotion/nokogiri/issues/2430

**Comment by danwt** [comment]
Wow amazing, thanks!
