### ISSUE TITLE
git missing

### ISSUE THREAD

**Issue by pviotti** [BretFisher/jekyll-serve#75]
Hi @BretFisher, thanks for this project - it really saves a lot of trouble with Ruby gems. 
When I run `docker run -p 4000:4000 -v $(pwd):/site bretfisher/jekyll-serve` in the folder of my project, after a long series of fetch/install logs, I get this error message:

```bash
Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.
Configuration file: /site/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /site
       Destination: /site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Liquid Exception: No such file or directory - git in /_layouts/default.liquid
/usr/local/bundle/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/metadata_drop.rb:90:in ``': No such file or directory - git (Errno::ENOENT)
	from /usr/local/bundle/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/metadata_drop.rb:90:in `build_revision'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/drops/drop.rb:52:in `public_send'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/drops/drop.rb:52:in `[]'
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/context.rb:197:in `lookup_and_evaluate'
[...cut long stacktrace...]
jekyll 3.9.2 | Error:  No such file or directory - git
```

It seems in the liquid template I have some tags that extracts the git revision using `git` command, but `git` is not installed, so it fails. 
Could you please add git to the image or suggest a workaround?

**Comment by BretFisher** [comment]
git added!
